global using System.IO.Compression;
global using System.Net.Http;
global using System.Runtime.CompilerServices;
global using System.Text;
global using GeoConvert;
global using MapBundle;
global using Replicant;
global using TUnit.Core;
global using TUnit.Assertions;
global using TUnit.Assertions.Extensions;
global using static VerifyTUnit.Verifier;
